services:
  traefik:
    image: traefik:v3.3
    command:
      - --api.insecure=true
      - --providers.docker
      - --log.level=DEBUG
      - --accesslog
      - --experimental.localPlugins.rewrite.moduleName=github.com/fojman/rewrite

    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/plugins-local/src/github.com/fojman/rewrite/
    tty: true

  whoami:
    image: traefik/whoami # https://github.com/traefik/whoami
    command: >-
      -name whoami -verbose true
    labels:
      traefik.http.routers.rewrite.rule: Host(`rw.localhost`)
      traefik.http.routers.rewrite.middlewares: rewrite

      traefik.http.middlewares.rewrite.plugin.rewrite.providers[0].name: pm
      traefik.http.middlewares.rewrite.plugin.rewrite.providers[0].version: 1.1.1
      traefik.http.middlewares.rewrite.plugin.rewrite.providers[0].rtp: 22
      traefik.http.middlewares.rewrite.plugin.rewrite.providers[0].super: zzzz
